/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChildrenRouteImport } from './routes/_authenticated/children'
import { Route as AuthenticatedClassroomRouteImport } from './routes/_authenticated/classroom'
import { Route as AuthenticatedCreateStoryRouteImport } from './routes/_authenticated/create-story'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSelectProfileRouteImport } from './routes/_authenticated/select-profile'
import { Route as AuthenticatedVocabularyRouteImport } from './routes/_authenticated/vocabulary'
import { Route as AuthenticatedStoryStoryIdRouteImport } from './routes/_authenticated/story.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChildrenRoute = AuthenticatedChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassroomRoute = AuthenticatedClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateStoryRoute =
  AuthenticatedCreateStoryRouteImport.update({
    id: '/create-story',
    path: '/create-story',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectProfileRoute =
  AuthenticatedSelectProfileRouteImport.update({
    id: '/select-profile',
    path: '/select-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVocabularyRoute = AuthenticatedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryStoryIdRoute =
  AuthenticatedStoryStoryIdRouteImport.update({
    id: '/story/$storyId',
    path: '/story/$storyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/classroom': typeof AuthenticatedClassroomRoute
  '/create-story': typeof AuthenticatedCreateStoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/select-profile': typeof AuthenticatedSelectProfileRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/story/$storyId': typeof AuthenticatedStoryStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/classroom': typeof AuthenticatedClassroomRoute
  '/create-story': typeof AuthenticatedCreateStoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/select-profile': typeof AuthenticatedSelectProfileRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/story/$storyId': typeof AuthenticatedStoryStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/children': typeof AuthenticatedChildrenRoute
  '/_authenticated/classroom': typeof AuthenticatedClassroomRoute
  '/_authenticated/create-story': typeof AuthenticatedCreateStoryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/select-profile': typeof AuthenticatedSelectProfileRoute
  '/_authenticated/vocabulary': typeof AuthenticatedVocabularyRoute
  '/_authenticated/story/$storyId': typeof AuthenticatedStoryStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/children'
    | '/classroom'
    | '/create-story'
    | '/dashboard'
    | '/select-profile'
    | '/vocabulary'
    | '/story/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/children'
    | '/classroom'
    | '/create-story'
    | '/dashboard'
    | '/select-profile'
    | '/vocabulary'
    | '/story/$storyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/children'
    | '/_authenticated/classroom'
    | '/_authenticated/create-story'
    | '/_authenticated/dashboard'
    | '/_authenticated/select-profile'
    | '/_authenticated/vocabulary'
    | '/_authenticated/story/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/children': {
      id: '/_authenticated/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AuthenticatedChildrenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classroom': {
      id: '/_authenticated/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof AuthenticatedClassroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-story': {
      id: '/_authenticated/create-story'
      path: '/create-story'
      fullPath: '/create-story'
      preLoaderRoute: typeof AuthenticatedCreateStoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-profile': {
      id: '/_authenticated/select-profile'
      path: '/select-profile'
      fullPath: '/select-profile'
      preLoaderRoute: typeof AuthenticatedSelectProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocabulary': {
      id: '/_authenticated/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthenticatedVocabularyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story/$storyId': {
      id: '/_authenticated/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof AuthenticatedStoryStoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChildrenRoute: typeof AuthenticatedChildrenRoute
  AuthenticatedClassroomRoute: typeof AuthenticatedClassroomRoute
  AuthenticatedCreateStoryRoute: typeof AuthenticatedCreateStoryRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSelectProfileRoute: typeof AuthenticatedSelectProfileRoute
  AuthenticatedVocabularyRoute: typeof AuthenticatedVocabularyRoute
  AuthenticatedStoryStoryIdRoute: typeof AuthenticatedStoryStoryIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChildrenRoute: AuthenticatedChildrenRoute,
  AuthenticatedClassroomRoute: AuthenticatedClassroomRoute,
  AuthenticatedCreateStoryRoute: AuthenticatedCreateStoryRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSelectProfileRoute: AuthenticatedSelectProfileRoute,
  AuthenticatedVocabularyRoute: AuthenticatedVocabularyRoute,
  AuthenticatedStoryStoryIdRoute: AuthenticatedStoryStoryIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
